### ISSUE TITLE
[Feature] Virionの説明

### ISSUE THREAD

**Issue by uramnoil** [defrag-pmmp-info/Defragmentation-of-PocketMine-Information#4]
**載せたほうが良いと考える分野は何ですか？**
Virionの説明とできればサンプル

**どのように載せるべきであると考えますか？**
Poggitを説明したファイルに追加するか、`dictionary/poggit/`を作成してPoggit.mdとVirion.mdで分ける。

**その他**

**Comment by UramnOIL** [comment]
コミットミスってログを汚しちゃいました。
62f4b7dが本物です。
